#!/usr/bin/env bash

## Copyright (C) 2020-2026 Aditya Shakya <adi1090x@gmail.com>

# directory
DIR="$HOME/.config/xmonad"

# Run networkmanager_dmenu with alternate config
networkmanager_dmenu --config "$DIR"/theme/networkmenu_config.ini
